language: r

r: release

os: linux
dist: xenial

before_install:
 - echo "options(repos=c(CRAN = 'http://cran.rstudio.com'))" > ~/.Rprofile

warnings_are_errors: true

# use --as-cran for more draconian checks
r_check_args: --run-dontrun
cache: packages

r_binary_packages:
 - ape
 - phangorn

